name: Generate Trophy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/trophy.svg
          theme: radical
          max-rows: 1
          margin-width: 10
          margin-height: 10

      - name: Deploy Trophy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: trophy-output
